# Generated by Django 4.1.1 on 2022-10-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0003_alter_task_options_task_complete_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
